### ISSUE TITLE
Got Error

### ISSUE THREAD

**Issue by tcagkansokmen** [rennokki/laravel-aws-eb#27]
I'm using AWS ElasticBeanstalk & Codepipeline with github.

I added .ebextensions folder to my project.
After deploy, it gives error below:
2020-09-07 10:02:39,677 [ERROR] Command 02_install_node_dependencies (sudo npm install) failed
2020-09-07 10:02:39,677 [ERROR] Error encountered during build of postbuild_0_Form: Command 02_install_node_dependencies failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command 02_install_node_dependencies failed
2020-09-07 10:02:39,678 [ERROR] -----------------------BUILD FAILED!------------------------
2020-09-07 10:02:39,678 [ERROR] Unhandled exception during build: Command 02_install_node_dependencies failed
Traceback (most recent call last):
  File "/opt/aws/bin/cfn-init", line 171, in <module>
    worklog.build(metadata, configSets)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 129, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 530, in build
    self.run_config(config, worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command 02_install_node_dependencies failed

**Comment by tcagkansokmen** [comment]
My elasticbeanstalk platform: PHP 7.3 running on 64bit Amazon Linux/2.9.9

**Comment by tcagkansokmen** [comment]
Here's my logs:

2020/09/07 09:34:21.122841 [INFO] Running command /bin/sh -c systemctl show -p PartOf amazon-cloudwatch-agent.service
2020/09/07 09:34:21.134126 [INFO] Running command /bin/sh -c systemctl stop amazon-cloudwatch-agent.service
2020/09/07 09:34:21.142661 [INFO] Executing instruction: GetToggleForceRotate
2020/09/07 09:34:21.142674 [INFO] Checking if logs need forced rotation
2020/09/07 09:34:21.142702 [INFO] Running command /bin/sh -c /opt/aws/bin/cfn-get-metadata -s arn:aws:cloudformation:eu-central-1:181576634659:stack/awseb-e-uibdih3hqw-stack/e0a0b230-f0eb-11ea-b398-0a3417f4b6e8 -r AWSEBAutoScalingGroup --region eu-central-1
2020/09/07 09:34:21.760525 [INFO] Running command /bin/sh -c /opt/aws/bin/cfn-get-metadata -s arn:aws:cloudformation:eu-central-1:181576634659:stack/awseb-e-uibdih3hqw-stack/e0a0b230-f0eb-11ea-b398-0a3417f4b6e8 -r AWSEBBeanstalkMetadata --region eu-central-1
2020/09/07 09:34:22.163083 [INFO] Procfile not found. Generating default rsyslog config
2020/09/07 09:34:22.164172 [INFO] Running command /bin/sh -c systemctl restart rsyslog.service
2020/09/07 09:34:22.183859 [INFO] Executing instruction: PostBuildEbExtension
2020/09/07 09:34:22.183888 [INFO] Starting executing the config set Infra-EmbeddedPostBuild.
2020/09/07 09:34:22.183911 [INFO] Running command /bin/sh -c /opt/aws/bin/cfn-init -s arn:aws:cloudformation:eu-central-1:181576634659:stack/awseb-e-uibdih3hqw-stack/e0a0b230-f0eb-11ea-b398-0a3417f4b6e8 -r AWSEBAutoScalingGroup --region eu-central-1 --configsets Infra-EmbeddedPostBuild
2020/09/07 09:34:22.579531 [ERROR] An error occurred during execution of command [app-deploy] - [PostBuildEbExtension]. Stop running the command. Error: Container commands build failed. Please refer to /var/log/cfn-init.log for more details. 

2020/09/07 09:34:22.579549 [INFO] Executing cleanup logic
2020/09/07 09:34:22.579647 [INFO] CommandService Response: {"status":"FAILURE","api_version":"1.0","results":[{"status":"FAILURE","msg":"Engine execution has encountered an error.","returncode":1,"events":[{"msg":"Instance deployment failed. For details, see 'eb-engine.log'.","timestamp":1599471262,"severity":"ERROR"}]}]}

2020/09/07 09:34:22.579850 [INFO] Platform Engine finished execution on command: app-deploy

2020/09/07 09:37:51.439591 [INFO] Starting...
2020/09/07 09:37:51.439642 [INFO] Starting EBPlatform-PlatformEngine
2020/09/07 09:37:51.439658 [INFO] reading event message file
2020/09/07 09:37:51.439784 [INFO] no eb envtier info file found, skip loading env tier info.
2020/09/07 09:37:51.439851 [INFO] Engine received EB command cfn-hup-exec

2020/09/07 09:37:51.505237 [INFO] Running command /bin/sh -c /opt/aws/bin/cfn-get-metadata -s arn:aws:cloudformation:eu-central-1:181576634659:stack/awseb-e-uibdih3hqw-stack/e0a0b230-f0eb-11ea-b398-0a3417f4b6e8 -r AWSEBAutoScalingGroup --region eu-central-1
2020/09/07 09:37:51.857633 [INFO] Running command /bin/sh -c /opt/aws/bin/cfn-get-metadata -s arn:aws:cloudformation:eu-central-1:181576634659:stack/awseb-e-uibdih3hqw-stack/e0a0b230-f0eb-11ea-b398-0a3417f4b6e8 -r AWSEBBeanstalkMetadata --region eu-central-1
2020/09/07 09:37:52.208382 [INFO] checking whether command tail-log is applicable to this instance...
2020/09/07 09:37:52.208396 [INFO] this command is applicable to the instance, thus instance should execute command
2020/09/07 09:37:52.208400 [INFO] Engine command: (tail-log)

2020/09/07 09:37:52.208451 [INFO] Executing instruction: GetTailLogs
2020/09/07 09:37:52.208456 [INFO] Tail Logs...
2020/09/07 09:37:52.208729 [INFO] Running command /bin/sh -c tail -n 100 /var/log/eb-engine.log

**Comment by tcagkansokmen** [comment]
cfn-init.log

2020-09-07 09:34:22,560 [ERROR] Command 00_copy_env_file (mv /tmp/.env /var/app/staging/.env) failed
2020-09-07 09:34:22,560 [ERROR] Error encountered during build of postbuild_0_Form: Command 00_copy_env_file failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command 00_copy_env_file failed
2020-09-07 09:34:22,562 [ERROR] -----------------------BUILD FAILED!------------------------
2020-09-07 09:34:22,562 [ERROR] Unhandled exception during build: Command 00_copy_env_file failed
Traceback (most recent call last):
  File "/opt/aws/bin/cfn-init", line 171, in <module>
    worklog.build(metadata, configSets)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 129, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 530, in build
    self.run_config(config, worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command 00_copy_env_file failed

**Comment by rennokki** [comment]
Check the logs section on the EB app and try to find in the archive u download, through the files, any other occurrence where it states that the command failed.

I assume you don't need to run the npm install in the deploy configuration.

**Comment by tcagkansokmen** [comment]
It looks like, it has never begin to download any archive?
I tried on my local again, and it installed with no problem.

What could cause this problem? I cant investigate, but there's only that error.

**Comment by tcagkansokmen** [comment]
I have found: sudo: npm: command not found

It looks like theres no npm installed?

**Comment by rennokki** [comment]
Make sure you got the `.platform` folder in the deployment and this file is not commented: https://github.com/rennokki/laravel-aws-eb/blob/master/.platform/hooks/prebuild/install_latest_node_js.sh

**Comment by tcagkansokmen** [comment]
no problem about files. but it keeps the same error.
can it be ignore .platform folder?

**Comment by tcagkansokmen** [comment]
is there any problem about my platform?

it is: PHP 7.4 running on 64bit Amazon Linux 2/3.1.1

**Comment by tcagkansokmen** [comment]
2020/09/07 12:41:07.866821 [ERROR] An error occurred during execution of command [app-deploy] - [RunAppDeployPreBuildHooks]. Stop running the command. Error: Command .platform/hooks/prebuild/configure_php_ini.sh failed with error fork/exec .platform/hooks/prebuild/configure_php_ini.sh: permission denied 


now it gives that error...

**Comment by rennokki** [comment]
Read the first lines from the installation on setting permissions: https://github.com/rennokki/laravel-aws-eb#installation

Also, if you are running on Windows, check https://github.com/rennokki/laravel-aws-eb/issues/17 with the subsequent issues.
