### ISSUE TITLE
Node.Js failed 

### ISSUE THREAD

**Issue by fleet-app** [rennokki/laravel-aws-eb#62]
as using your package, I got one issue with `sudo npm install`

maybe, I am doing wrong as I'm trying deployed the laravel project with your eb, seems all fine until sudo npm install failed

```
2021-10-20 10:48:34,072 [INFO] -----------------------Starting build-----------------------
2021-10-20 10:48:34,079 [INFO] Running configSets: Infra-EmbeddedPostBuild
2021-10-20 10:48:34,082 [INFO] Running configSet Infra-EmbeddedPostBuild
2021-10-20 10:48:34,086 [INFO] Running config postbuild_0_Ergnation_rowing
2021-10-20 10:48:34,103 [INFO] Command 00_copy_env_file succeeded
2021-10-20 10:48:36,241 [INFO] Command 01_install_composer_dependencies succeeded
2021-10-20 10:48:36,263 [ERROR] Command 02_install_node_dependencies (sudo npm install) failed
2021-10-20 10:48:36,263 [ERROR] Error encountered during build of postbuild_0_Ergnation_rowing: Command 02_install_node_dependencies failed
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 573, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 273, in build
    self._config.commands)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/command_tool.py", line 127, in apply
    raise ToolError(u"Command %s failed" % name)
cfnbootstrap.construction_errors.ToolError: Command 02_install_node_dependencies failed
2021-10-20 10:48:36,266 [ERROR] -----------------------BUILD FAILED!------------------------
2021-10-20 10:48:36,266 [ERROR] Unhandled exception during build: Command 02_install_node_dependencies failed
Traceback (most recent call last):
  File "/opt/aws/bin/cfn-init", line 176, in <module>
    worklog.build(metadata, configSets)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 135, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 561, in build
    self.run_config(config, worklog)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 573, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 273, in build
    self._config.commands)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/command_tool.py", line 127, in apply
    raise ToolError(u"Command %s failed" % name)
cfnbootstrap.construction_errors.ToolError: Command 02_install_node_dependencies failed
```

**Comment by dominikager** [comment]
@fleet-app download the full logs of Elasticbeanstalk and there is one file "cfn-init-cmd.log". There you can find everything you need.

**Comment by hilal-hipster** [comment]
@rennokki 
Error from **cfn-init.log**
```
2022-08-01 08:51:13,354 [ERROR] Command 03build_node_assets (sudo npm run prod) failed
2022-08-01 08:51:13,354 [ERROR] Error encountered during build of postbuild_0_bettrcloudbar_webportal: Command 03build_node_assets failed
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 576, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 276, in build
    self._config.commands)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/command_tool.py", line 127, in apply
    raise ToolError(u"Command %s failed" % name)
cfnbootstrap.construction_errors.ToolError: Command 03build_node_assets failed
2022-08-01 08:51:13,357 [ERROR] -----------------------BUILD FAILED!------------------------
2022-08-01 08:51:13,357 [ERROR] Unhandled exception during build: Command 03build_node_assets failed
Traceback (most recent call last):
  File "/opt/aws/bin/cfn-init", line 176, in <module>
    worklog.build(metadata, configSets)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 137, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 564, in build
    self.run_config(config, worklog)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 576, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 276, in build
    self._config.commands)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/command_tool.py", line 127, in apply
    raise ToolError(u"Command %s failed" % name)
cfnbootstrap.construction_errors.ToolError: Command 03build_node_assets failed
```

Error from **cfn-init-cmd.log**
```
2022-08-01 08:51:12,565 P12210 [INFO] Command 03build_node_assets
2022-08-01 08:51:13,353 P12210 [INFO] -----------------------Command Output-----------------------
2022-08-01 08:51:13,353 P12210 [INFO] 	
2022-08-01 08:51:13,353 P12210 [INFO] 	> prod
2022-08-01 08:51:13,353 P12210 [INFO] 	> npm run production
2022-08-01 08:51:13,353 P12210 [INFO] 	
2022-08-01 08:51:13,353 P12210 [INFO] 	
2022-08-01 08:51:13,353 P12210 [INFO] ------------------------------------------------------------
2022-08-01 08:51:13,353 P12210 [ERROR] Exited with error code 243
```
Error from **eb-engine.log**
```
2022/08/01 08:51:13.393640 [INFO] Error occurred during build: Command 03build_node_assets failed

2022/08/01 08:51:13.393885 [ERROR] An error occurred during execution of command [app-deploy] - [PostBuildEbExtension]. Stop running the command. Error: Container commands build failed. Please refer to /var/log/cfn-init.log for more details. 

2022/08/01 08:51:13.393889 [INFO] Executing cleanup logic
2022/08/01 08:51:13.405229 [INFO] CommandService Response: {"status":"FAILURE","api_version":"1.0","results":[{"status":"FAILURE","msg":"Engine execution has encountered an error.","returncode":1,"events":[{"msg":"Instance deployment failed. For details, see 'eb-engine.log'.","timestamp":1659343873393,"severity":"ERROR"}]}]}
```
